### ISSUE TITLE
works模块如何编辑

### ISSUE THREAD

**Issue by fenglir** [leadream/hexo-theme-juuust#2]
搭完以后，页面中只有Recent Posts 模块 不显示 works栏目  我在source文件夹中新建了works文件夹放入md文档，页面还是没有显示，因为我只是一个ui设计 所以前端问题有些不懂，希望可以指点一下，谢谢

**Comment by hallee9000** [comment]
@fenglir 你应该没有在自己的项目中写这个文件`source/_data/heroes.yml` ，这个文件里面定义了你要精选的文章。具体可以参考这一段：https://github.com/leadream/hexo-theme-juuust#6%E7%B2%BE%E9%80%89%E4%BD%9C%E5%93%81

**Comment by hallee9000** [comment]
@fenglir 不用新建 works 文件夹，你要做的是从自己的文章里面选几个出来，把它的标题链接什么的写在`source/_data/heroes.yml` 里。

**Comment by fenglir** [comment]
不好意思 又来打扰了 现在遇到了两个问题

1  精选作品 案例1 点击后没有页面显示。页面显示结果为Cannot GET /data/md/

我在 source/_data/heroes.yml  中  写入的link: /data/md （我在md文件夹中放了文件，我刚刚以为是因为yml文件里面的data前后没有空格的原因，但是试了下还是不行  ）

<img width="695" alt="2018-08-31 3 15 44" src="https://user-images.githubusercontent.com/37427895/44899565-b1576700-ad34-11e8-9284-19a543940f67.png">


2   精选作品的more按钮 和导航栏按钮点下后会跳转到文章页面 且文章按钮显示选中效果 没有显示精选页面  （关于页面同样会跳转到作品）

**Comment by hallee9000** [comment]
@fenglir link 不是文件夹路径，而是网站中文章的链接，参考：https://coding.net/u/leadream/p/hexo-theme-juuust/git/blob/master/_data/heroes.yml#L6

第二个问题，你应该是没有在 source 下面创建对应的 about/index.html、works/index.html 文件。
参考我的这个完整搭建：https://coding.net/u/leadream/p/hexo-theme-juuust/git
