### ISSUE TITLE
page跳转

### ISSUE THREAD

**Issue by fenglir** [leadream/hexo-theme-juuust#3]
文章第二页不能跳转，按照之前的提示，我新建了在page文件夹里面又新建了一个2文件夹里面放了index文件，但是点击跳转后，页面其实还是第一页，同时下面跳转器消失了，我感觉应该是index里面的命名有问题，查看了源码里面也没有，想问下第二页命名应该是什么？

**Comment by hallee9000** [comment]
@fenglir 不需要你自己去分页面的，只需要像我这样把所有文章放在一个文件夹中，它自己在生成时会给你分好页。请参考：
https://coding.net/u/leadream/p/hexo-theme-juuust/git/tree/master/source/_posts

**Comment by fenglir** [comment]
文档都是在_posts的 但是page2无法打开，

http://fenglir.com

**Comment by hallee9000** [comment]
@fenglir 没试出来，建议贴一下你的 `_config.yml` 。

**Comment by fenglir** [comment]
@leadream 
<img width="368" alt="1" src="https://user-images.githubusercontent.com/37427895/45130823-db89a880-b1bc-11e8-96aa-0c07127f4fb4.png">


<img width="1190" alt="2" src="https://user-images.githubusercontent.com/37427895/45130865-1db2ea00-b1bd-11e8-9a4f-f2ae28283c6f.png">

<img width="1004" alt="2018-09-06 10 10 00" src="https://user-images.githubusercontent.com/37427895/45130895-3b804f00-b1bd-11e8-8088-849a104b360f.png">

**Comment by hallee9000** [comment]
@fenglir 看起来没有问题，你再试一次 `hexo g` 看看。

**Comment by fenglir** [comment]
@leadream Cannot GET /page/2/ 还是会有这个问题

**Comment by fenglir** [comment]
@leadream 找到问题了 不好意思

**Comment by fenglir** [comment]
@leadream 找到问题了 不好意思浪费你时间了 是文章刚好9篇  所以第二页不显示

**Comment by hallee9000** [comment]
@fenglir  那为啥翻页器会出现第二页呢？ 😕

**Comment by fenglir** [comment]
@leadream 这个问题我就不太清楚了  刚刚我文章刚好是9篇会出现翻页器但是点击后没有页面显示 增加到10篇后页面就正常了
